// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: volpe.proto

package grpc_comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_volpe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Seed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int32                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_volpe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{1}
}

func (x *Seed) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type PopulationSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopulationSize) Reset() {
	*x = PopulationSize{}
	mi := &file_volpe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulationSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationSize) ProtoMessage() {}

func (x *PopulationSize) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationSize.ProtoReflect.Descriptor instead.
func (*PopulationSize) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{2}
}

func (x *PopulationSize) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_volpe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{3}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Individual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genotype      []byte                 `protobuf:"bytes,1,opt,name=genotype,proto3" json:"genotype,omitempty"`
	Fitness       float32                `protobuf:"fixed32,2,opt,name=fitness,proto3" json:"fitness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Individual) Reset() {
	*x = Individual{}
	mi := &file_volpe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Individual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Individual) ProtoMessage() {}

func (x *Individual) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Individual.ProtoReflect.Descriptor instead.
func (*Individual) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{4}
}

func (x *Individual) GetGenotype() []byte {
	if x != nil {
		return x.Genotype
	}
	return nil
}

func (x *Individual) GetFitness() float32 {
	if x != nil {
		return x.Fitness
	}
	return 0
}

type Population struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Individual          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Population) Reset() {
	*x = Population{}
	mi := &file_volpe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Population) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Population) ProtoMessage() {}

func (x *Population) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Population.ProtoReflect.Descriptor instead.
func (*Population) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{5}
}

func (x *Population) GetMembers() []*Individual {
	if x != nil {
		return x.Members
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_volpe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Reply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_volpe_proto protoreflect.FileDescriptor

const file_volpe_proto_rawDesc = "" +
	"\n" +
	"\vvolpe.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x04Seed\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x05R\x04seed\"$\n" +
	"\x0ePopulationSize\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\n" +
	"Individual\x12\x1a\n" +
	"\bgenotype\x18\x01 \x01(\fR\bgenotype\x12\x18\n" +
	"\afitness\x18\x02 \x01(\x02R\afitness\"3\n" +
	"\n" +
	"Population\x12%\n" +
	"\amembers\x18\x01 \x03(\v2\v.IndividualR\amembers\"L\n" +
	"\x05Reply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2\xa4\x02\n" +
	"\x0eVolpeContainer\x12(\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"\x00\x12\x1f\n" +
	"\fInitFromSeed\x12\x05.Seed\x1a\x06.Reply\"\x00\x12/\n" +
	"\x16InitFromSeedPopulation\x12\v.Population\x1a\x06.Reply\"\x00\x123\n" +
	"\x11GetBestPopulation\x12\x0f.PopulationSize\x1a\v.Population\"\x00\x121\n" +
	"\x14AdjustPopulationSize\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00\x12.\n" +
	"\x11RunForGenerations\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00B\x0eZ\f./grpc_commsb\x06proto3"

var (
	file_volpe_proto_rawDescOnce sync.Once
	file_volpe_proto_rawDescData []byte
)

func file_volpe_proto_rawDescGZIP() []byte {
	file_volpe_proto_rawDescOnce.Do(func() {
		file_volpe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volpe_proto_rawDesc), len(file_volpe_proto_rawDesc)))
	})
	return file_volpe_proto_rawDescData
}

var file_volpe_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_volpe_proto_goTypes = []any{
	(*HelloRequest)(nil),   // 0: HelloRequest
	(*Seed)(nil),           // 1: Seed
	(*PopulationSize)(nil), // 2: PopulationSize
	(*HelloReply)(nil),     // 3: HelloReply
	(*Individual)(nil),     // 4: Individual
	(*Population)(nil),     // 5: Population
	(*Reply)(nil),          // 6: Reply
}
var file_volpe_proto_depIdxs = []int32{
	4, // 0: Population.members:type_name -> Individual
	0, // 1: VolpeContainer.SayHello:input_type -> HelloRequest
	1, // 2: VolpeContainer.InitFromSeed:input_type -> Seed
	5, // 3: VolpeContainer.InitFromSeedPopulation:input_type -> Population
	2, // 4: VolpeContainer.GetBestPopulation:input_type -> PopulationSize
	2, // 5: VolpeContainer.AdjustPopulationSize:input_type -> PopulationSize
	2, // 6: VolpeContainer.RunForGenerations:input_type -> PopulationSize
	3, // 7: VolpeContainer.SayHello:output_type -> HelloReply
	6, // 8: VolpeContainer.InitFromSeed:output_type -> Reply
	6, // 9: VolpeContainer.InitFromSeedPopulation:output_type -> Reply
	5, // 10: VolpeContainer.GetBestPopulation:output_type -> Population
	6, // 11: VolpeContainer.AdjustPopulationSize:output_type -> Reply
	6, // 12: VolpeContainer.RunForGenerations:output_type -> Reply
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_volpe_proto_init() }
func file_volpe_proto_init() {
	if File_volpe_proto != nil {
		return
	}
	file_volpe_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volpe_proto_rawDesc), len(file_volpe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volpe_proto_goTypes,
		DependencyIndexes: file_volpe_proto_depIdxs,
		MessageInfos:      file_volpe_proto_msgTypes,
	}.Build()
	File_volpe_proto = out.File
	file_volpe_proto_goTypes = nil
	file_volpe_proto_depIdxs = nil
}
