// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: volpe_container.proto

package container

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "volpe-framework/comms/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_volpe_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Seed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int32                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_volpe_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{1}
}

func (x *Seed) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type PopulationSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopulationSize) Reset() {
	*x = PopulationSize{}
	mi := &file_volpe_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulationSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationSize) ProtoMessage() {}

func (x *PopulationSize) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationSize.ProtoReflect.Descriptor instead.
func (*PopulationSize) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{2}
}

func (x *PopulationSize) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_volpe_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{3}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_volpe_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{4}
}

func (x *Reply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_volpe_container_proto protoreflect.FileDescriptor

const file_volpe_container_proto_rawDesc = "" +
	"\n" +
	"\x15volpe_container.proto\x1a\fcommon.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x04Seed\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x05R\x04seed\"$\n" +
	"\x0ePopulationSize\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x05Reply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa4\x02\n" +
	"\x0eVolpeContainer\x12(\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"\x00\x12\x1f\n" +
	"\fInitFromSeed\x12\x05.Seed\x1a\x06.Reply\"\x00\x12/\n" +
	"\x16InitFromSeedPopulation\x12\v.Population\x1a\x06.Reply\"\x00\x123\n" +
	"\x11GetBestPopulation\x12\x0f.PopulationSize\x1a\v.Population\"\x00\x121\n" +
	"\x14AdjustPopulationSize\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00\x12.\n" +
	"\x11RunForGenerations\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00B\x13Z\x11./comms/containerb\x06proto3"

var (
	file_volpe_container_proto_rawDescOnce sync.Once
	file_volpe_container_proto_rawDescData []byte
)

func file_volpe_container_proto_rawDescGZIP() []byte {
	file_volpe_container_proto_rawDescOnce.Do(func() {
		file_volpe_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volpe_container_proto_rawDesc), len(file_volpe_container_proto_rawDesc)))
	})
	return file_volpe_container_proto_rawDescData
}

var file_volpe_container_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_volpe_container_proto_goTypes = []any{
	(*HelloRequest)(nil),      // 0: HelloRequest
	(*Seed)(nil),              // 1: Seed
	(*PopulationSize)(nil),    // 2: PopulationSize
	(*HelloReply)(nil),        // 3: HelloReply
	(*Reply)(nil),             // 4: Reply
	(*common.Population)(nil), // 5: Population
}
var file_volpe_container_proto_depIdxs = []int32{
	0, // 0: VolpeContainer.SayHello:input_type -> HelloRequest
	1, // 1: VolpeContainer.InitFromSeed:input_type -> Seed
	5, // 2: VolpeContainer.InitFromSeedPopulation:input_type -> Population
	2, // 3: VolpeContainer.GetBestPopulation:input_type -> PopulationSize
	2, // 4: VolpeContainer.AdjustPopulationSize:input_type -> PopulationSize
	2, // 5: VolpeContainer.RunForGenerations:input_type -> PopulationSize
	3, // 6: VolpeContainer.SayHello:output_type -> HelloReply
	4, // 7: VolpeContainer.InitFromSeed:output_type -> Reply
	4, // 8: VolpeContainer.InitFromSeedPopulation:output_type -> Reply
	5, // 9: VolpeContainer.GetBestPopulation:output_type -> Population
	4, // 10: VolpeContainer.AdjustPopulationSize:output_type -> Reply
	4, // 11: VolpeContainer.RunForGenerations:output_type -> Reply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_volpe_container_proto_init() }
func file_volpe_container_proto_init() {
	if File_volpe_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volpe_container_proto_rawDesc), len(file_volpe_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volpe_container_proto_goTypes,
		DependencyIndexes: file_volpe_container_proto_depIdxs,
		MessageInfos:      file_volpe_container_proto_msgTypes,
	}.Build()
	File_volpe_container_proto = out.File
	file_volpe_container_proto_goTypes = nil
	file_volpe_container_proto_depIdxs = nil
}
